name: user_profile_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  expansion_tile_card: ^2.0.0
  lottie: ^1.1.0
  mailer: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: 'assets/icon/app_icon.png'
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
  plugin:
    platforms:
      android:
        package: io.kommunicate.kommunicate_flutter_plugin
        pluginClass: KommunicateFlutterPlugin
      ios:
        pluginClass: KommunicateFlutterPlugin